### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by helloTsubasa** [helloTsubasa/fleamarket_sample_78g#71]
■ URL
IPアドレス：http://54.95.108.70/
Github（最終課題のリポジトリ）：https://github.com/helloTsubasa/fleamarket_sample_78g

■ Basic認証
ID：admin
Pass：password78g

■ テスト用アカウント
◯ 購入者用
メールアドレス：buyer_user@gmail.com
パスワード：1234567

◯ 購入用カード情報
番号：4242424242424242
期限：2 / 22
セキュリティカード：123

◯ 出品者用
メールアドレス：seller_user@gmail.com
パスワード：1234567

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○出品内容・販売価格が適切でない（公序良俗・著作権に反する画像を使用したり、不適切な文言を使用していない）**
→芸能人の写真の使用は控えましょう

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by helloTsubasa** [comment]
写真は削除しました。無念です…

**Comment by helloTsubasa** [comment]
> ご提出ありがとうございます！
> 挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
> 
> **○出品内容・販売価格が適切でない（公序良俗・著作権に反する画像を使用したり、不適切な文言を使用していない）**
> →芸能人の写真の使用は控えましょう
> 
> 修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
> https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by mutorisa** [comment]
再度ご提出及び写真の削除をありがとうございました！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
